export const VERSION='1.0.0';
export const preQuestions=[
 {objective:'Preço e pressa',text:'Uma fritadeira de R$ 799 aparece por R$ 199, só por alguns minutos. O que fazer?',options:['Pagar logo para garantir o preço.','Parar e comparar a oferta em canais oficiais.','Confiar porque o anúncio tem uma foto bonita.'],correct:1,explanation:'Preço muito baixo e urgência pedem uma pausa. Compare em canais oficiais acessados por você.'},
 {objective:'Endereço e empresa',text:'Qual verificação ajuda a avaliar se uma loja é quem diz ser?',options:['Olhar apenas as estrelas das avaliações.','Conferir só o cadeado do endereço.','Comparar o endereço com o canal oficial e verificar os dados da empresa.'],correct:2,explanation:'Cadeado e estrelas não comprovam a identidade da loja. Confira o endereço completo e os dados em fontes independentes.'},
 {objective:'Pagamento e destinatário',text:'A loja só aceita Pix e mostra um destinatário diferente da empresa. Qual atitude é mais prudente?',options:['Interromper e verificar a relação do destinatário com a loja.','Pagar porque o desconto é grande.','Ignorar o nome porque qualquer Pix é seguro.'],correct:0,explanation:'A exigência de pagamento por Pix e um destinatário sem vínculo comprovado com a loja são sinais para interromper a compra e investigar.'}
];
export const postQuestions=[
 {objective:'Preço e pressa',text:'Uma cafeteira de R$ 600 está por R$ 149 e o anúncio diz “última chance”. O que fazer?',options:['Confiar porque há muitas curtidas.','Pagar antes de comparar.','Parar e comparar em canais oficiais.'],correct:2,explanation:preQuestions[0].explanation},
 {objective:'Endereço e empresa',text:'Uma página parece ser de uma loja conhecida. Como investigar sua identidade?',options:['Conferir o endereço completo e os dados da empresa em fontes independentes.','Confiar apenas no cadeado.','Confiar nas avaliações publicadas na própria página.'],correct:0,explanation:preQuestions[1].explanation},
 {objective:'Pagamento e destinatário',text:'Um site oferece desconto só no Pix para uma pessoa sem vínculo explicado com a loja. O que fazer?',options:['Pagar para aproveitar o desconto.','Interromper e verificar o vínculo antes de decidir.','Confiar porque aparece um nome no pagamento.'],correct:1,explanation:preQuestions[2].explanation}
];
export const risks=[
 {key:'inspecionou_preco',title:'Preço muito abaixo do anunciado',detail:'Fritadeira Brisa 4 L: de R$ 799 por R$ 199. Oferta criada para esta atividade.',explanation:'Um desconto muito grande merece comparação em canais oficiais. O preço, isoladamente, não prova fraude.'},
 {key:'inspecionou_urgencia',title:'Pressão do relógio',detail:'O anúncio diz “apenas 2 unidades”. O relógio é fictício e a atividade continua quando ele termina.',explanation:'Contagem regressiva e escassez podem pressionar uma decisão. Você pode parar e investigar, mesmo quando a oferta diz que está acabando.'},
 {key:'inspecionou_url',title:'Endereço parecido com o de uma loja',detail:'Endereço simulado: ofertas-casa-br1sa.invalid. Compare com o nome Casa Brisa. Este texto não é um link e não abre outro site.',explanation:'O número 1 no lugar da letra i e palavras extras podem imitar outro endereço. Digite o endereço oficial por conta própria; o cadeado não comprova a identidade da loja.'},
 {key:'inspecionou_empresa',title:'Dados da empresa',detail:'Casa Brisa Comércio. CNPJ informado: 00.000.000/0000-00. Endereço: Rua da Simulação, 000. Atendimento: não informado. Trocas: “fale com a loja”, sem canal.',explanation:'Um CNPJ escrito na página não confirma legitimidade. Verifique registro, endereço, atendimento e políticas em fontes independentes. Aqui os dados são inválidos e os canais incompletos.'},
 {key:'inspecionou_avaliacoes',title:'Avaliações sem verificação',detail:'A loja exibe oito comentários atribuídos a Mariana Souza, Paulo Henrique, Luciana Ferreira, Carlos Eduardo, Renata Oliveira, André Santos, Camila Ribeiro e Juliana Costa. Todos têm 5 estrelas, sem data, foto ou confirmação de compra.',explanation:'Elogios uniformes na própria loja não comprovam reputação. Busque opiniões independentes e histórico de atendimento.'},
 {key:'inspecionou_pagamento',title:'Pix exclusivo e cartão indisponível',detail:'A loja oferece 50% de desconto no Pix: R$ 99,50. Cartão indisponível: “sistema em manutenção, use Pix”. Não há outra forma de pagamento.',explanation:'Desconto condicionado e pressão para usar apenas Pix pedem atenção. Não escolha uma forma de pagamento só porque a loja insiste.'},
 {key:'inspecionou_destinatario',title:'Destinatário diferente da empresa',detail:'Destinatário ilustrativo: Pessoa Exemplo da Simulação. Tipo: pessoa física. Relação com Casa Brisa: não informada. Nenhuma chave ou código Pix é disponibilizado.',explanation:'O destinatário é diferente da empresa e seu vínculo não foi explicado. Confira quem recebe e interrompa se a relação não puder ser verificada.'}
];
export const shareText='PARE • CONFIRA • COMPRE\nPARE: desconfie de preço muito baixo e pressão de tempo.\nCONFIRA: endereço oficial, dados da empresa, reputação independente e destinatário do pagamento.\nCOMPRE: só depois de verificar; se houver suspeita, interrompa.\nCompras Seguras — simulação educativa.';
export function score(questions,answers){return questions.reduce((n,q,i)=>n+(q.correct===answers[i]?1:0),0)}
export class Session {
 constructor({now=()=>performance.now(),id=()=>crypto.randomUUID(),save=()=>{},onEvent=()=>{}}={}){this.now=now;this.save=save;this.onEvent=onEvent;this.start=now();this.data={version:VERSION,id:id(),events:[],pre:null,post:null,outcome:null,analysisMs:0};this.stage='welcome';this.visible=true;this.segment=null;this.firstBuy=null;this.decided=false;this.stageTimes={welcome:0};this.stageStarted=this.start;}
 accumulateStage(){if(this.stageStarted!==null){this.stageTimes[this.stage]=(this.stageTimes[this.stage]||0)+Math.max(0,this.now()-this.stageStarted);this.stageStarted=null}}
 changeStage(stage){this.accumulateStage();this.stage=stage;this.stageTimes[stage]??=0;this.stageStarted=this.visible?this.now():null;this.persist()}
 finishStageTimes(){this.accumulateStage();for(const [stage,duration] of Object.entries(this.stageTimes)){if(stage==='result')continue;this.event('tempo_etapa_'+stage,{durationMs:Math.round(duration)})}}
 persist(){this.save(this.data)}
 event(name,extra={}){if(this.data.events.some(e=>e.name===name))return;this.data.events.push({name,stage:this.stage,elapsedMs:Math.max(0,Math.round(this.now()-this.start)),...extra});this.persist();try{this.onEvent(this.data.events.at(-1),this.data)}catch{}}
 enterStore(){if(this.segment===null&&!this.decided){this.segment=this.visible?this.now():null;this.event('entrou_na_loja')}}
 analysis(){return this.data.analysisMs+(this.segment===null?0:this.now()-this.segment)}
 visibility(visible){this.accumulateStage();this.stageStarted=visible?this.now():null;if(!visible&&this.segment!==null){this.data.analysisMs+=this.now()-this.segment;this.segment=null}this.visible=visible;if(visible&&!this.decided&&this.data.events.some(e=>e.name==='entrou_na_loja'))this.segment??=this.now();this.persist()}
 buy(){if(this.firstBuy!==null)return;this.firstBuy=this.analysis();this.event('clicou_comprar',{analysisMs:Math.round(this.firstBuy)});if(this.firstBuy<15000)this.event('compra_precipitada')}
 decide(outcome){if(this.decided)return;this.data.analysisMs=Math.round(this.analysis());this.segment=null;this.decided=true;this.data.outcome=outcome;this.event(outcome==='purchase'?'aceitou_pix_suspeito':'desistiu_por_suspeita');this.event('tempo_total_analise',{valueMs:this.data.analysisMs});this.persist()}
 quiz(kind,answers){const questions=kind==='pre'?preQuestions:postQuestions;this.data[kind]={answers:[...answers],score:score(questions,answers)};if(kind==='post')this.finishStageTimes();this.event(kind==='pre'?'respondeu_quiz_inicial':'respondeu_quiz_final');this.persist()}
 has(name){return this.data.events.some(e=>e.name===name)}
}
