import test from 'node:test';
import assert from 'node:assert/strict';
import {Session,score,preQuestions,postQuestions,risks,shareText} from '../js/model.js';
function clock(){let time=0;const session=new Session({now:()=>time,id:()=>Math.random().toString()});return {session,advance:ms=>time+=ms}}
test('T04.2, T09.1: ambos os quizzes pontuam de 0 a 3 e têm gabarito único',()=>{for(const questions of [preQuestions,postQuestions])for(let hits=0;hits<=3;hits++){const answers=questions.map((q,i)=>i<hits?q.correct:(q.correct+1)%3);assert.equal(score(questions,answers),hits);assert.equal(questions.length,3);questions.forEach(q=>assert.ok(q.options[q.correct]&&q.explanation))}});
test('T07.2: limiar do primeiro clique 14,9 / 15 / 15,1 segundos',()=>{for(const ms of [14900,15000,15100]){const c=clock();c.session.stage='store';c.session.enterStore();c.advance(ms);c.session.buy();assert.equal(c.session.has('compra_precipitada'),ms<15000);c.advance(20000);c.session.buy();assert.equal(c.session.data.events.filter(e=>e.name==='clicou_comprar').length,1)}});
test('T07.4: aba oculta descontada e decisão encerra relógio',()=>{const c=clock();c.session.enterStore();c.advance(10000);c.session.visibility(false);c.advance(20000);c.session.visibility(true);c.advance(5000);c.session.decide('purchase');assert.equal(c.session.data.analysisMs,15000);c.advance(60000);assert.equal(c.session.analysis(),15000)});
test('T07.3: PIX só na confirmação; desistência explícita',()=>{const c=clock();c.session.enterStore();c.session.buy();assert.equal(c.session.has('aceitou_pix_suspeito'),false);c.session.decide('quit');assert.equal(c.session.has('desistiu_por_suspeita'),true);assert.equal(c.session.has('aceitou_pix_suspeito'),false);c.session.decide('purchase');assert.equal(c.session.data.outcome,'quit')});
test('T07.1, T07.5: eventos únicos, etapas e sessão nova limpa',()=>{const c=clock();c.session.stage='guide';c.session.event('apresentou_guia_inicial');c.session.stage='store';c.advance(1000);c.session.event('consultou_infografico');c.session.event('inspecionou_rodape');c.session.event('inspecionou_empresa');c.session.event('inspecionou_empresa');assert.equal(c.session.data.events.length,4);assert.equal(c.session.data.events[1].stage,'store');assert.equal(c.session.data.events[1].elapsedMs,1000);const fresh=clock().session;assert.notEqual(fresh.data.id,c.session.data.id);assert.equal(fresh.data.events.length,0);assert.equal(fresh.data.pre,null)});
test('T09.2: respostas preservadas, comparação melhora/empate/queda',()=>{for(const [before,after] of [[1,3],[2,2],[3,0]]){const s=clock().session;for(const [kind,qs,hits] of [['pre',preQuestions,before],['post',postQuestions,after]]){const answers=qs.map((q,i)=>i<hits?q.correct:(q.correct+1)%3);s.quiz(kind,answers);answers[0]=99;assert.equal(s.data[kind].score,hits);assert.notEqual(s.data[kind].answers[0],99)}}});
test('T01: objetivos equivalentes, sete riscos; cartão sem dados de sessão',()=>{assert.deepEqual(preQuestions.map(q=>q.objective),postQuestions.map(q=>q.objective));assert.equal(new Set(risks.map(r=>r.key)).size,7);risks.forEach(r=>assert.ok(r.detail&&r.explanation));assert.ok(shareText.includes('PARE • CONFIRA • COMPRE'));assert.ok(!/pontuação|respostas|session|CPF/.test(shareText))});
test('T07.4: começar com aba oculta não conta tempo; desistência no anúncio = zero',()=>{const c=clock();c.session.visibility(false);c.session.enterStore();c.advance(20000);c.session.visibility(true);c.advance(3000);c.session.decide('quit');assert.equal(c.session.data.analysisMs,3000);assert.equal(clock().session.analysis(),0)});
